name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  test-and-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # чтобы оставлять комментарии

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov ruff mypy requests openai

      - name: Create build dir
        run: mkdir -p build

      - name: Ruff (lint)
        continue-on-error: true
        run: |
          ruff check . | tee build/__ruff.txt

      - name: Mypy (types)
        continue-on-error: true
        run: |
          mypy . | tee build/__mypy.txt

      - name: PyTest
        continue-on-error: true
        run: |
          pytest -q --disable-warnings --maxfail=1 --cov=. 2>&1 | tee build/__pytest_stdout.txt

      - name: AI Review comment
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }} # если нужно
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/ai_review.py

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: build
