# .github/workflows/gh-pages.yml
name: Deploy docs
on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
